name: Build KookyWolf ROM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install WSL and Ubuntu
        run: |
          wsl --install -d Ubuntu
          wsl sudo apt update
          wsl sudo apt install -y bc bison build-essential curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses-dev lib32readline-dev lib32z1-dev libc6-dev-i386 libgl1-mesa-dev libncurses6 libncurses-dev libssl-dev libx11-dev libxml2-utils lzop openjdk-11-jdk pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev wget

      - name: Install repo tool
        run: |
          wsl curl https://storage.googleapis.com/git-repo-downloads/repo -o repo
          wsl chmod +x repo
          wsl sudo mv repo /usr/local/bin/

      - name: Sync ROM source
        run: |
          wsl repo init -u https://github.com/LineageOS/android.git -b lineage-21.0
          wsl repo sync -j$(wsl nproc --all)

      - name: Apply KookyWolf branding
        run: |
          wsl bash -c "echo 'ro.build.display.id=KookyWolf ROM' >> build/make/core/build_id.mk"
          wsl bash -c "echo 'ro.build.version.incremental=kookywolf_$(date +%Y%m%d)' >> build/make/core/build_id.mk"
          wsl bash -c "echo 'ro.modversion=KookyWolf-ROM' >> build/make/core/build_id.mk"
          wsl sed -i 's/About phone/About KookyWolf ROM/g' packages/apps/Settings/res/values/strings.xml || true
          wsl sed -i 's/LineageOS/KookyWolf ROM/g' packages/apps/Settings/res/values/strings.xml || true
          wsl sed -i 's/System UI Tuner/KookyWolf UI Tuner/g' frameworks/base/packages/SystemUI/res/values/strings.xml || true

      - name: Download custom boot animation
        run: |
          wsl mkdir -p vendor/bootanimation
          wsl wget -O vendor/bootanimation/bootanimation.zip https://xdaforums.com/attachments/bootanimation-zip.2986805/

      - name: Add boot animation to ROM
        run: |
          wsl bash -c "mkdir -p out/target/product/\$(grep 'PRODUCT_DEVICE' device/*/*/BoardConfig.mk | cut -d'=' -f2 | head -n1)/system/media"
          wsl bash -c "echo 'PRODUCT_COPY_FILES += vendor/bootanimation/bootanimation.zip:system/media/bootanimation.zip' >> device/*/*/device.mk"

      - name: Lunch and Build
        run: |
          wsl bash -c "source build/envsetup.sh && lunch lineage_<device>-userdebug && make -j\$(nproc --all)"

      - name: Upload KookyWolf ROM
        uses: actions/upload-artifact@v4
        with:
          name: KookyWolf-ROM
          path: out/target/product/*/*.zip
